name = "cf-icon"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[build]
module_rules = [
  { type = "Wasm", name = "WASM_MODULE", path = "node_modules/@jsquash/resize/lib/resize/pkg/squoosh_resize_bg.wasm" }
]